language: go
sudo: required
go:
  - "1.11"
  - "1.12"
  - "1.13"
  - "1.14"

env:
  - GO111MODULE=on AWS_ACCESS_KEY_ID=AKID AWS_SECRET_ACCESS_KEY=SECRET

services:
  - docker

before_install:
  - go mod download

install: true

script:
  - docker run -d -p 8000:8000 dwmkerr/dynamodb
  - go test -v ./...
