name: Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.21', '1.22']
    name: Go ${{ matrix.go }}
    services:
      dynamodb:
        image: amazon/dynamodb-local
        ports:
          - 8000:8000
    steps:
      - uses: actions/checkout@v3
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - name: Download gomodules
        run: go mod download
      - name: Run tests
        run: go test -v ./...
        env:
          AWS_ACCESS_KEY_ID: AKID
          AWS_SECRET_ACCESS_KEY: SECRET

